---
apiVersion: network.azure.jet.crossplane.io/v1alpha2
kind: Subnet
metadata:
  name: naresh-subnet
spec:
  forProvider:
    resourceGroupNameRef:
      name: naresh-rg
    virtualNetworkNameRef:
      name: naresh-vn
    addressPrefixes:
      - 10.0.0.0/25
  providerConfigRef:
    name: azure-jet-provider-config 
